{"sid": "2ab8410573de4ec098d82aa441b2e8f2", "uid": null, "qid": "0ccad9970a2943748a034f7e511e2544", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [0ccad9970a2943748a034f7e511e2544]\nTraceback (most recent call last):\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/workspaces/Openfabic/app/main.py\", line 57, in execute\n    logging.info(f\"User prompt: {user_prompt}\")\n                                 ^^^^^^^^^^^\nNameError: name 'user_prompt' is not defined\n", "created_at": "2025-06-08T09:38:42.120217"}], "status": "FAILED", "created_at": "2025-06-08T09:38:38.788697", "updated_at": "2025-06-08T09:38:42.120252", "finished": true}