{"sid": "05b4df7654d341d392ab95f6676b9b26", "uid": null, "qid": "eafc631c6bb64f10918b1885e4a80f79", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [eafc631c6bb64f10918b1885e4a80f79]\nTraceback (most recent call last):\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/workspaces/Openfabic/app/main.py\", line 71, in execute\n    object = stub.call('f0997a01d6d3a5fe53d8561300318557', {'prompt': 'expanded_prompt'}, 'super-user')\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/Openfabic/app/core/stub.py\", line 85, in call\n    raise Exception(f\"Connection not found for app ID: {app_id}\")\nException: Connection not found for app ID: f0997a01d6d3a5fe53d8561300318557\n", "created_at": "2025-06-08T09:54:43.716692"}], "status": "FAILED", "created_at": "2025-06-08T09:54:41.542414", "updated_at": "2025-06-08T09:54:43.716727", "finished": true}