{"sid": "808420d60b8c4daa887e4550eb3e3626", "uid": null, "qid": "8b5f1dbfb2504736b55de2274485ebec", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [8b5f1dbfb2504736b55de2274485ebec]\nTraceback (most recent call last):\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/workspaces/Openfabic/app/main.py\", line 73, in execute\n    object = stub.call('f0997a01-d6d3-a5fe-53d8-561300318557', {'prompt': 'expanded_prompt'}, 'super-user')\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/Openfabic/app/core/stub.py\", line 85, in call\n    raise Exception(f\"Connection not found for app ID: {app_id}\")\nException: Connection not found for app ID: f0997a01-d6d3-a5fe-53d8-561300318557\n", "created_at": "2025-06-08T10:07:33.358615"}], "status": "FAILED", "created_at": "2025-06-08T10:07:30.138474", "updated_at": "2025-06-08T10:07:33.358641", "finished": true}